project: terraform-digitalocean-cluster
version: 1.4.5
author: Joel Lefkowitz
verbose_name: Terraform DigitalOcean cluster
html_title: Terraform DigitalOcean cluster 
github_url: https://github.com/JoelLefkowitz/env-git
